version: "2"
run:
  timeout: 5m
  tests: false
linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
  settings:
    staticcheck:
      checks:
        - all
        - '-ST1005'
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
