// Code generated by go generate; DO NOT EDIT.
// This file was generated by vendorize.py
// At $timeStamp

package config

/* All these constants are defined in the vendor.conf file
 */
const (
	Provider        = "$providerURL"
	ApplicationName = "$applicationName"
	BinaryName      = "$binaryName"
	DonateURL       = "$donateURL"
	HelpURL         = "$helpURL"
	TosURL          = "$tosURL"
	APIURL          = "$apiURL"
	GeolocationAPI  = "$geolocationAPI"
)

/*

CaCert : a string containing a representation of the provider CA, used to
        sign the webapp and openvpn certificates. should be placed in
        config/[provider]-ca.crt

*/
var CaCert = []byte(`$caCertString`)
