/*
   DO NOT EDIT --------------------------------------------------

   This file has been automatically generated by `go generate`.
   Any changes will be overriden.

   DO NOT EDIT --------------------------------------------------
*/

package config

/* All these constants are defined in the vendor.conf file
*/
const (
	Provider        = "$providerURL"
	ApplicationName = "$applicationName"
	BinaryName      = "$binaryName"
	DonateURL       = "$donateURL"
	HelpURL         = "$helpURL"
	TosURL          = "$tosURL"
	APIURL          = "$apiURL"
	GeolocationAPI  = "$geolocationAPI"
)

/*

CaCert : a string containing a representation of the provider CA, used to
        sign the webapp and openvpn certificates. should be placed in
        config/[provider]-ca.crt

*/
var CaCert = []byte(`$caCertString`)
