// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"bn":    &dictionary{index: bnIndex, data: bnData},
		"en_GB": &dictionary{index: en_GBIndex, data: en_GBData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"es":    &dictionary{index: esIndex, data: esData},
		"es_ES": &dictionary{index: es_ESIndex, data: es_ESData},
		"eu":    &dictionary{index: euIndex, data: euData},
		"fr":    &dictionary{index: frIndex, data: frData},
		"it":    &dictionary{index: itIndex, data: itData},
		"lt":    &dictionary{index: ltIndex, data: ltData},
		"nl":    &dictionary{index: nlIndex, data: nlData},
		"pt_BR": &dictionary{index: pt_BRIndex, data: pt_BRData},
		"ro":    &dictionary{index: roIndex, data: roData},
		"ru":    &dictionary{index: ruIndex, data: ruData},
		"sk":    &dictionary{index: skIndex, data: skData},
		"sv":    &dictionary{index: svIndex, data: svData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%[1]s is an easy, fast, and secure VPN service from %[2]s. %[1]s does not require a user account, keep logs, or track you in any way.\n\t    \nThis service is paid for entirely by donations from users like you. Please donate at %[3]s.\n\t\t\nBy using this application, you agree to the Terms of Service available at %[4]s. This service is provided as-is, without any warranty, and is intended for people who work to make the world a better place.\n\n\n%[1]v version: %[5]s": 2,
	"%s blocking internet": 23,
	"%s off":               18,
	"%s on":                17,
	"About":                3,
	"About...":             14,
	"An error has ocurred initializing the VPN: %v": 24,
	"Can't connect to %s: %v":                       7,
	"Cancel":                                        19,
	"Checking status...":                            9,
	"Connecting to %s":                              20,
	"Could not find a polkit authentication agent. Please run one and try again.": 5,
	"Donate":                       1,
	"Donate...":                    13,
	"Error starting VPN":           8,
	"Help...":                      12,
	"Initialization error":         4,
	"Missing authentication agent": 6,
	"Quit":                         15,
	"Reconnect":                    22,
	"Route traffic through:":       25,
	"Stopping %s":                  21,
	"The %s service is expensive to run. Because we don't want to store personal information about you, there are no accounts or billing for this service. But if you want the service to continue, donate at least $5 each month.\n\t\nDo you want to donate now?": 0,
	"Turn off":          11,
	"Turn on":           10,
	"Use %s %v gateway": 16,
}

var bnIndex = []uint32{ // 27 elements
	0x00000000, 0x000000fe, 0x00000111, 0x000002e0,
	0x000002f9, 0x0000031c, 0x00000410, 0x0000045e,
	0x000004b1, 0x00000501, 0x00000548, 0x0000055c,
	0x00000570, 0x00000589, 0x0000059f, 0x000005bb,
	0x000005c8, 0x0000060d, 0x00000620, 0x00000633,
	0x00000643, 0x00000683, 0x000006a6, 0x000006c2,
	0x0000070a, 0x0000076f, 0x0000076f,
} // Size: 132 bytes

const bnData string = "" + // Size: 1903 bytes
	"\x02The %[1]s service is expensive to run. Because we don't want to stor" +
	"e personal information about you, there are no accounts or billing for t" +
	"his service. But if you want the service to continue, donate at least $5" +
	" each month.\x0a\x09\x0aDo you want to donate now?\x02অনুদান\x02%[1]s is" +
	" an easy, fast, and secure VPN service from %[2]s. %[1]s does not requir" +
	"e a user account, keep logs, or track you in any way.\x0a\x09    \x0aThi" +
	"s service is paid for entirely by donations from users like you. Please " +
	"donate at %[3]s.\x0a\x09\x09\x0aBy using this application, you agree to " +
	"the Terms of Service available at %[4]s. This service is provided as-is," +
	" without any warranty, and is intended for people who work to make the w" +
	"orld a better place.\x0a\x0a\x0a%[1]v version: %[5]s\x02সম্পর্কে\x02সূচন" +
	"া ত্রুটি\x02পোলকিট প্রমাণীকরণ এজেন্ট খুঁজে পাওয়া যায়নি. অনুগ্রহ করে " +
	"একটি চালান এবং আবার চেষ্টা করুন ।\x02প্রমাণীকরণ এজেন্ট অনুপস্থিত\x02" +
	"\u00a0%[1]s: %[2]v সাথে সংযোগ করতে পারবেন না\x02ভিপিএন চালু করতে ত্রুটি " +
	"হয়েছে\x02অবস্থা পরিক্ষা করা হচ্ছে ...\x02চালু কর\x02বন্ধ কর\x02সাহায্য" +
	"...\x02অনুদান...\x02সম্পর্কে...\x02বন্ধ\x02%[1]s %[2]v গেটওয়ে ব্যবহার ক" +
	"রুন\x02%[1]s চালু\x02%[1]s বন্ধ\x02বাতিল\x02%[1]s এর সাথে সংযুক্ত হচ্ছ" +
	"ে\x02%[1]s বন্ধ হচ্ছে\x02পুনঃসংযোগ\x02%[1]s ইন্টারনেট প্রতিরোধ করছে" +
	"\x02VPN আরম্ভ করার সময় একটি ত্রুটি ঘটেছে: %[1]v"

var en_GBIndex = []uint32{ // 27 elements
	0x00000000, 0x000000fe, 0x00000105, 0x000002d4,
	0x000002da, 0x000002ef, 0x0000033b, 0x00000358,
	0x00000376, 0x00000389, 0x0000039c, 0x000003a4,
	0x000003ad, 0x000003b5, 0x000003bf, 0x000003c8,
	0x000003cd, 0x000003e5, 0x000003ee, 0x000003f8,
	0x000003ff, 0x00000413, 0x00000422, 0x0000042c,
	0x00000444, 0x00000475, 0x00000475,
} // Size: 132 bytes

const en_GBData string = "" + // Size: 1141 bytes
	"\x02The %[1]s service is expensive to run. Because we don't want to stor" +
	"e personal information about you, there are no accounts or billing for t" +
	"his service. But if you want the service to continue, donate at least $5" +
	" each month.\x0a\x09\x0aDo you want to donate now?\x02Donate\x02%[1]s is" +
	" an easy, fast, and secure VPN service from %[2]s. %[1]s does not requir" +
	"e a user account, keep logs, or track you in any way.\x0a\x09    \x0aThi" +
	"s service is paid for entirely by donations from users like you. Please " +
	"donate at %[3]s.\x0a\x09\x09\x0aBy using this application, you agree to " +
	"the Terms of Service available at %[4]s. This service is provided as-is," +
	" without any warranty, and is intended for people who work to make the w" +
	"orld a better place.\x0a\x0a\x0a%[1]v version: %[5]s\x02About\x02Initial" +
	"isation error\x02Could not find a Polkit authentication agent. Please ru" +
	"n one and try again.\x02Missing authentication agent\x02Can't connect to" +
	" %[1]s: %[2]v\x02Error starting VPN\x02Checking status...\x02Turn on\x02" +
	"Turn off\x02Help...\x02Donate...\x02About...\x02Quit\x02Use %[1]s %[2]v " +
	"gateway\x02%[1]s on\x02%[1]s off\x02Cancel\x02Connecting to %[1]s\x02Sto" +
	"pping %[1]s\x02Reconnect\x02%[1]s blocking Internet\x02An error has ocur" +
	"red initializing the VPN: %[1]v"

var en_USIndex = []uint32{ // 27 elements
	0x00000000, 0x000000fe, 0x00000105, 0x000002d4,
	0x000002da, 0x000002ef, 0x0000033b, 0x00000358,
	0x00000376, 0x00000389, 0x0000039c, 0x000003a4,
	0x000003ad, 0x000003b5, 0x000003bf, 0x000003c8,
	0x000003cd, 0x000003e5, 0x000003ee, 0x000003f8,
	0x000003ff, 0x00000413, 0x00000422, 0x0000042c,
	0x00000444, 0x00000475, 0x0000048c,
} // Size: 132 bytes

const en_USData string = "" + // Size: 1164 bytes
	"\x02The %[1]s service is expensive to run. Because we don't want to stor" +
	"e personal information about you, there are no accounts or billing for t" +
	"his service. But if you want the service to continue, donate at least $5" +
	" each month.\x0a\x09\x0aDo you want to donate now?\x02Donate\x02%[1]s is" +
	" an easy, fast, and secure VPN service from %[2]s. %[1]s does not requir" +
	"e a user account, keep logs, or track you in any way.\x0a\x09    \x0aThi" +
	"s service is paid for entirely by donations from users like you. Please " +
	"donate at %[3]s.\x0a\x09\x09\x0aBy using this application, you agree to " +
	"the Terms of Service available at %[4]s. This service is provided as-is," +
	" without any warranty, and is intended for people who work to make the w" +
	"orld a better place.\x0a\x0a\x0a%[1]v version: %[5]s\x02About\x02Initial" +
	"ization error\x02Could not find a polkit authentication agent. Please ru" +
	"n one and try again.\x02Missing authentication agent\x02Can't connect to" +
	" %[1]s: %[2]v\x02Error starting VPN\x02Checking status...\x02Turn on\x02" +
	"Turn off\x02Help...\x02Donate...\x02About...\x02Quit\x02Use %[1]s %[2]v " +
	"gateway\x02%[1]s on\x02%[1]s off\x02Cancel\x02Connecting to %[1]s\x02Sto" +
	"pping %[1]s\x02Reconnect\x02%[1]s blocking internet\x02An error has ocur" +
	"red initializing the VPN: %[1]v\x02Route traffic through:"

var esIndex = []uint32{ // 27 elements
	0x00000000, 0x0000012a, 0x0000012f, 0x000002fe,
	0x00000308, 0x00000321, 0x00000388, 0x000003aa,
	0x000003cd, 0x000003e5, 0x000003fe, 0x00000407,
	0x0000040e, 0x00000417, 0x0000041f, 0x0000042c,
	0x00000433, 0x00000454, 0x00000464, 0x00000472,
	0x0000047b, 0x0000048e, 0x000004a5, 0x000004b7,
	0x000004d1, 0x00000502, 0x00000502,
} // Size: 132 bytes

const esData string = "" + // Size: 1282 bytes
	"\x02El servicio %[1]s es costoso de mantener. Debido a que no queremos a" +
	"lmacenar información personal sobre los usuarios, no hay cuentas ni sist" +
	"ema de facturación en este servicio. Pero si deseas que el servicio cont" +
	"inúe, puedes donar al menos 5 USD al mes.\x0a\x09\x0a¿Quieres realizar l" +
	"a donación ahora?\x02Dona\x02%[1]s is an easy, fast, and secure VPN serv" +
	"ice from %[2]s. %[1]s does not require a user account, keep logs, or tra" +
	"ck you in any way.\x0a\x09    \x0aThis service is paid for entirely by d" +
	"onations from users like you. Please donate at %[3]s.\x0a\x09\x09\x0aBy " +
	"using this application, you agree to the Terms of Service available at %" +
	"[4]s. This service is provided as-is, without any warranty, and is inten" +
	"ded for people who work to make the world a better place.\x0a\x0a\x0a%[1" +
	"]v version: %[5]s\x02Acerca de\x02Error de inicialización\x02No se pudo " +
	"encontrar ningún agente de autenticacion de polkit. Por favor lanza uno " +
	"y prueba de nuevo.\x02Falta un agente de autenticación\x02No puedo conec" +
	"tar con %[1]s: %[2]v\x02Error arrancando la VPN\x02Comprobando el estado" +
	"...\x02Encender\x02Apagar\x02Ayuda...\x02Dona...\x02Acerca de...\x02Cerr" +
	"ar\x02Usa la salida de %[1]s por %[2]v\x02%[1]s encendida\x02%[1]s apaga" +
	"da\x02Cancelar\x02Conectando a %[1]s\x02Desconectando de %[1]s\x02Volver" +
	" a conectar\x02%[1]s bloqueando internet\x02Ha ocurrido un error inicial" +
	"izando la VPN: %[1]v"

var es_ESIndex = []uint32{ // 27 elements
	0x00000000, 0x000000fe, 0x00000104, 0x000002d3,
	0x000002dd, 0x000002f6, 0x00000357, 0x00000376,
	0x0000039a, 0x000003ae, 0x000003c4, 0x000003cc,
	0x000003d7, 0x000003e0, 0x000003e9, 0x000003f6,
	0x000003fc, 0x0000041c, 0x0000042b, 0x0000043d,
	0x00000446, 0x00000459, 0x0000046a, 0x00000474,
	0x0000048e, 0x000004bf, 0x000004bf,
} // Size: 132 bytes

const es_ESData string = "" + // Size: 1215 bytes
	"\x02The %[1]s service is expensive to run. Because we don't want to stor" +
	"e personal information about you, there are no accounts or billing for t" +
	"his service. But if you want the service to continue, donate at least $5" +
	" each month.\x0a\x09\x0aDo you want to donate now?\x02Donar\x02%[1]s is " +
	"an easy, fast, and secure VPN service from %[2]s. %[1]s does not require" +
	" a user account, keep logs, or track you in any way.\x0a\x09    \x0aThis" +
	" service is paid for entirely by donations from users like you. Please d" +
	"onate at %[3]s.\x0a\x09\x09\x0aBy using this application, you agree to t" +
	"he Terms of Service available at %[4]s. This service is provided as-is, " +
	"without any warranty, and is intended for people who work to make the wo" +
	"rld a better place.\x0a\x0a\x0a%[1]v version: %[5]s\x02Acerca de\x02Erro" +
	"r de inicialización\x02No se pudo encontrar un agente de autenticación p" +
	"olkit. Por favor corre uno e intenta de nuevo.\x02Falta agente de autent" +
	"icación\x02No se puede conectar a %[1]s: %[2]v\x02Error iniciando VPN" +
	"\x02Comprobando estado...\x02Activar\x02Desactivar\x02Ayuda...\x02Donar." +
	"..\x02Acerca de...\x02Salir\x02Usar ruta de salida %[1]s %[2]v\x02%[1]s " +
	"activada\x02%[1]s desactivada\x02Cancelar\x02Conectando a %[1]s\x02Deten" +
	"iendo %[1]s\x02Reconnect\x02%[1]s bloqueando Internet\x02An error has oc" +
	"urred initializing the VPN: %[1]v"

var euIndex = []uint32{ // 27 elements
	0x00000000, 0x000000fe, 0x0000010d, 0x000002dc,
	0x000002e7, 0x000002fc, 0x00000357, 0x00000377,
	0x0000039b, 0x000003b5, 0x000003cb, 0x000003d4,
	0x000003e0, 0x000003ec, 0x000003fe, 0x0000040c,
	0x00000412, 0x0000042f, 0x00000440, 0x00000454,
	0x00000459, 0x00000470, 0x00000480, 0x0000048d,
	0x000004a7, 0x000004d6, 0x000004d6,
} // Size: 132 bytes

const euData string = "" + // Size: 1238 bytes
	"\x02The %[1]s service is expensive to run. Because we don't want to stor" +
	"e personal information about you, there are no accounts or billing for t" +
	"his service. But if you want the service to continue, donate at least $5" +
	" each month.\x0a\x09\x0aDo you want to donate now?\x02Dohaintza egin\x02" +
	"%[1]s is an easy, fast, and secure VPN service from %[2]s. %[1]s does no" +
	"t require a user account, keep logs, or track you in any way.\x0a\x09   " +
	" \x0aThis service is paid for entirely by donations from users like you." +
	" Please donate at %[3]s.\x0a\x09\x09\x0aBy using this application, you a" +
	"gree to the Terms of Service available at %[4]s. This service is provide" +
	"d as-is, without any warranty, and is intended for people who work to ma" +
	"ke the world a better place.\x0a\x0a\x0a%[1]v version: %[5]s\x02Honi bur" +
	"uz\x02Errorea habiaraztean\x02Ezin da polkit autentifikazio agente bat b" +
	"ilatu. Mesedez, exekutatu bat eta berria saiatu.\x02Autentifikazio agent" +
	"ea falta da\x02Ezin da %[1]s(e)ra konektatu: %[2]v\x02Errorea VPNa habia" +
	"raztean\x02Egiaztatzen egoera...\x02Aktibatu\x02Desaktibatu\x02Laguntza." +
	"..\x02Dohaintza egin...\x02Honi buruz...\x02Irten\x02Erabili %[1]s %[2]v" +
	" atebidea\x02%[1]s aktibatuta\x02%[1]s desaktibatuta\x02Utzi\x02%[1]s(e)" +
	"ra konektatzen\x02%[1]s gelditzen\x02Birkonektatu\x02%[1]s internet blok" +
	"eatzen\x02Errore bat gertatu da VPNa habiaraztean: %[1]v"

var frIndex = []uint32{ // 27 elements
	0x00000000, 0x00000154, 0x00000161, 0x00000330,
	0x0000033a, 0x00000354, 0x000003b6, 0x000003e2,
	0x0000040f, 0x0000042b, 0x00000449, 0x00000451,
	0x0000045d, 0x00000465, 0x00000475, 0x00000482,
	0x0000048a, 0x000004ae, 0x000004c0, 0x000004d6,
	0x000004de, 0x000004f1, 0x00000501, 0x00000510,
	0x00000526, 0x0000056a, 0x0000056a,
} // Size: 132 bytes

const frData string = "" + // Size: 1386 bytes
	"\x02L’exploitation du service %[1]s coûte cher. Dans la mesure où ne nou" +
	"s voulons enregistrer aucun renseignement personnel à votre sujet, il n’" +
	"y ni compte ni facturation pour ce service. Mais si vous souhaitez toute" +
	"fois que le service continue, faites un don d’au moins 5\u00a0$ mensuell" +
	"ement\x0a\x09\x0aSouhaitez-vous faire un don maintenant\u2009?\x02Faire " +
	"un don\x02%[1]s is an easy, fast, and secure VPN service from %[2]s. %[1" +
	"]s does not require a user account, keep logs, or track you in any way." +
	"\x0a\x09    \x0aThis service is paid for entirely by donations from user" +
	"s like you. Please donate at %[3]s.\x0a\x09\x09\x0aBy using this applica" +
	"tion, you agree to the Terms of Service available at %[4]s. This service" +
	" is provided as-is, without any warranty, and is intended for people who" +
	" work to make the world a better place.\x0a\x0a\x0a%[1]v version: %[5]s" +
	"\x02À propos\x02Erreur d’initialisation\x02Impossible de trouver un agen" +
	"t d’authentification polkit. Veuillez en exécuter un et ressayer.\x02L’a" +
	"gent d’authentification est manquant\x02Impossible de se connecter à %[1" +
	"]s\u00a0: %[2]v\x02Erreur du démarrage du RPV\x02Vérification de l’état…" +
	"\x02Activer\x02Désactiver\x02Aide…\x02Faire un don…\x02À propos…\x02Quit" +
	"ter\x02Utiliser la passerelle %[1]s %[2]v\x0a\x02%[1]s est activé\x02%[1" +
	"]s est désactivé\x02Annuler\x02Connexion à %[1]s\x02Arrêt de %[1]s\x02Se" +
	" reconnecter\x02%[1]s bloque Internet\x02Une erreur est survenue lors de" +
	" l’\x0ainitialisation du RPV\u00a0: %[1]v"

var itIndex = []uint32{ // 27 elements
	0x00000000, 0x000000fe, 0x00000103, 0x000002d2,
	0x000002df, 0x000002fc, 0x00000348, 0x0000036a,
	0x00000388, 0x000003a4, 0x000003bd, 0x000003c5,
	0x000003cc, 0x000003d5, 0x000003dd, 0x000003ed,
	0x000003f2, 0x0000040a, 0x00000413, 0x0000041d,
	0x00000425, 0x00000439, 0x00000448, 0x00000453,
	0x0000046b, 0x0000049c, 0x0000049c,
} // Size: 132 bytes

const itData string = "" + // Size: 1180 bytes
	"\x02The %[1]s service is expensive to run. Because we don't want to stor" +
	"e personal information about you, there are no accounts or billing for t" +
	"his service. But if you want the service to continue, donate at least $5" +
	" each month.\x0a\x09\x0aDo you want to donate now?\x02Dona\x02%[1]s is a" +
	"n easy, fast, and secure VPN service from %[2]s. %[1]s does not require " +
	"a user account, keep logs, or track you in any way.\x0a\x09    \x0aThis " +
	"service is paid for entirely by donations from users like you. Please do" +
	"nate at %[3]s.\x0a\x09\x09\x0aBy using this application, you agree to th" +
	"e Terms of Service available at %[4]s. This service is provided as-is, w" +
	"ithout any warranty, and is intended for people who work to make the wor" +
	"ld a better place.\x0a\x0a\x0a%[1]v version: %[5]s\x02Informazioni\x02Er" +
	"rore nell'inizializzazione\x02Could not find a polkit authentication age" +
	"nt. Please run one and try again.\x02Agente di autenticazione mancante" +
	"\x02Can't connect to %[1]s: %[2]v\x02Errore nell'avvio della VPN\x02Cont" +
	"rollando lo stato...\x02Accendi\x02Spegni\x02Aiuto...\x02Dona...\x02Info" +
	"rmazioni...\x02Esci\x02Use %[1]s %[2]v gateway\x02%[1]s on\x02%[1]s off" +
	"\x02Annulla\x02Connettendo a %[1]s\x02Fermando %[1]s\x02Riconnetti\x02%[" +
	"1]s blocking internet\x02An error has ocurred initializing the VPN: %[1]" +
	"v"

var ltIndex = []uint32{ // 27 elements
	0x00000000, 0x0000013d, 0x00000146, 0x00000364,
	0x00000369, 0x0000037c, 0x000003e3, 0x00000408,
	0x00000431, 0x00000449, 0x0000045e, 0x00000467,
	0x00000471, 0x0000047c, 0x00000488, 0x00000490,
	0x00000498, 0x000004bd, 0x000004cc, 0x000004dc,
	0x000004e7, 0x000004fd, 0x0000050c, 0x00000522,
	0x0000053c, 0x00000563, 0x00000563,
} // Size: 132 bytes

const ltData string = "" + // Size: 1379 bytes
	"\x02%[1]s paslaugą brangiai kainuoja išlaikyti. Kadangi nenorime laikyti" +
	" jūsų asmeninės informacijos, todėl nėra jokių paskyrų ar apmokestinimo " +
	"už šią paslaugą. Tačiau, jei norite, kad paslauga būtų teikiama ir tolia" +
	"u, paaukokite kiekvieną mėnesį bent po $5 (JAV dolerius).\x0a\x09\x0aAr " +
	"norite paaukoti dabar?\x02Paaukoti\x02%[1]s yra lengva naudoti, greita i" +
	"r saugi VPN paslauga iš %[2]s. %[1]s nereikalauja naudotojo paskyros, ne" +
	"saugo žurnalų ir jokiu kitu būdu jūsų neseka.\x0a\x09    \x0aŠi paslauga" +
	" yra apmokama tik iš, tokių pačių naudotojų kaip jūs, paaukojimų. Prašom" +
	"e paaukokite, adresu %[3]s.\x0a\x09\x09\x0aNaudodami šią programą, sutin" +
	"kate su Naudojimosi Sąlygomis, kurias galite rasti adresu %[4]s. Ši pasl" +
	"auga yra teikiama esamu pavidalu, be jokių garantijų ir yra skirta žmonė" +
	"ms, kurie dirba, kad padarytų pasaulį geresnį.\x0a\x0a\x0a%[1]v versija:" +
	" %[5]s\x02Apie\x02Inicijavimo klaida\x02Nepavyko rasti politikos rinkini" +
	"o tapatybės nustatymo agento. Paleiskite jį ir bandykite dar kartą.\x02T" +
	"rūksta tapatybės nustatymo agento\x02Nepavyksta prisijungti prie %[1]s: " +
	"%[2]v\x02Klaida paleidžiant VPN\x02Tikrinama būsena...\x02Įjungti\x02Išj" +
	"ungti\x02Pagalba...\x02Paaukoti...\x02Apie...\x02Išeiti\x02Naudoti %[1]s" +
	" %[2]v tinklų sietuvą\x02%[1]s įjungta\x02%[1]s išjungta\x02Atsisakyti" +
	"\x02Jungiamasi prie %[1]s\x02Stabdoma %[1]s\x02Prisijungti iš naujo\x02%" +
	"[1]s blokuoja internetą\x02Inicijuojant VPN, įvyko klaida: %[1]v"

var nlIndex = []uint32{ // 27 elements
	0x00000000, 0x000000fe, 0x00000106, 0x000002d5,
	0x000002da, 0x000002ec, 0x0000033b, 0x00000358,
	0x0000037c, 0x0000039e, 0x000003b4, 0x000003c0,
	0x000003cd, 0x000003d5, 0x000003e0, 0x000003e8,
	0x000003f0, 0x0000040c, 0x00000416, 0x00000420,
	0x0000042a, 0x0000043e, 0x00000454, 0x0000045e,
	0x0000047b, 0x000004c5, 0x000004c5,
} // Size: 132 bytes

const nlData string = "" + // Size: 1221 bytes
	"\x02The %[1]s service is expensive to run. Because we don't want to stor" +
	"e personal information about you, there are no accounts or billing for t" +
	"his service. But if you want the service to continue, donate at least $5" +
	" each month.\x0a\x09\x0aDo you want to donate now?\x02Doneren\x02%[1]s i" +
	"s an easy, fast, and secure VPN service from %[2]s. %[1]s does not requi" +
	"re a user account, keep logs, or track you in any way.\x0a\x09    \x0aTh" +
	"is service is paid for entirely by donations from users like you. Please" +
	" donate at %[3]s.\x0a\x09\x09\x0aBy using this application, you agree to" +
	" the Terms of Service available at %[4]s. This service is provided as-is" +
	", without any warranty, and is intended for people who work to make the " +
	"world a better place.\x0a\x0a\x0a%[1]v version: %[5]s\x02Over\x02Initial" +
	"isatiefout\x02Kan geen polkit authenticatieagent vinden. Voer er een uit" +
	" en probeer opnieuw.\x02Authenticatieagent ontbreekt\x02Kan niet verbind" +
	"en met %[1]s: %[2]v\x02Fout bij het opstarten van de VPN\x02Status contr" +
	"oleren...\x02Inschakelen\x02Uitschakelen\x02Hulp...\x02Doneren...\x02Ove" +
	"r...\x02Stoppen\x02Gebruik %[1]s %[2]v gateway\x02%[1]s aan\x02%[1]s uit" +
	"\x02Annuleren\x02Verbinden met %[1]s\x02%[1]s aan het stoppen\x02Reconne" +
	"ct\x02%[1]s blokkeert het internet\x02Er heeft zich een fout voorgedaan " +
	"bij het initialiseren van de VPN: %[1]v"

var pt_BRIndex = []uint32{ // 27 elements
	0x00000000, 0x000000fe, 0x00000111, 0x000002e0,
	0x000002e6, 0x000002fe, 0x0000036f, 0x0000039a,
	0x000003c4, 0x000003da, 0x000003f0, 0x000003f6,
	0x000003ff, 0x00000408, 0x0000041e, 0x00000427,
	0x0000042c, 0x0000044a, 0x0000045d, 0x00000473,
	0x0000047c, 0x0000048f, 0x0000049d, 0x000004a7,
	0x000004c9, 0x000004fa, 0x000004fa,
} // Size: 132 bytes

const pt_BRData string = "" + // Size: 1274 bytes
	"\x02The %[1]s service is expensive to run. Because we don't want to stor" +
	"e personal information about you, there are no accounts or billing for t" +
	"his service. But if you want the service to continue, donate at least $5" +
	" each month.\x0a\x09\x0aDo you want to donate now?\x02Fazer uma doação" +
	"\x02%[1]s is an easy, fast, and secure VPN service from %[2]s. %[1]s doe" +
	"s not require a user account, keep logs, or track you in any way.\x0a" +
	"\x09    \x0aThis service is paid for entirely by donations from users li" +
	"ke you. Please donate at %[3]s.\x0a\x09\x09\x0aBy using this application" +
	", you agree to the Terms of Service available at %[4]s. This service is " +
	"provided as-is, without any warranty, and is intended for people who wor" +
	"k to make the world a better place.\x0a\x0a\x0a%[1]v version: %[5]s\x02S" +
	"obre\x02Erro na inicialização\x02Não foi possível encontrar um agente de" +
	" autenticação polkit. Por favor, execute um agente e tente novamente." +
	"\x02Um agente de autenticação está faltando\x02Não é possível conectar a" +
	" %[1]s: %[2]v\x02Erro ao iniciar a VPN\x02Verificando estado...\x02Ligar" +
	"\x02Desligar\x02Ajuda...\x02Fazer uma doação...\x02Sobre...\x02Sair\x02U" +
	"sar o gateway %[2]v de %[1]s\x02%[1]s está ligada\x02%[1]s está desligad" +
	"a\x02Cancelar\x02Conectando a %[1]s\x02Parando %[1]s\x02Reconnect\x02%[1" +
	"]s está bloqueando a Internet\x02An error has ocurred initializing the V" +
	"PN: %[1]v"

var roIndex = []uint32{ // 27 elements
	0x00000000, 0x00000117, 0x00000120, 0x000002ef,
	0x000002f6, 0x0000030e, 0x00000364, 0x00000387,
	0x000003ab, 0x000003c2, 0x000003d6, 0x000003e1,
	0x000003ec, 0x000003f6, 0x00000402, 0x0000040c,
	0x00000417, 0x00000439, 0x0000044a, 0x0000045b,
	0x00000463, 0x00000476, 0x00000483, 0x0000048f,
	0x000004b4, 0x000004e4, 0x000004e4,
} // Size: 132 bytes

const roData string = "" + // Size: 1252 bytes
	"\x02Serviciul %[1]s este scump pentru a rula. Deoarece nu dorim să stocă" +
	"m informații personale despre dvs., nu există conturi sau facturare pent" +
	"ru acest serviciu. Dar dacă doriți ca serviciul să continue, donați cel " +
	"puțin 5 USD în fiecare lună.\x0a\x09\x0aVreți să donați acum?\x02Donație" +
	"\x02%[1]s is an easy, fast, and secure VPN service from %[2]s. %[1]s doe" +
	"s not require a user account, keep logs, or track you in any way.\x0a" +
	"\x09    \x0aThis service is paid for entirely by donations from users li" +
	"ke you. Please donate at %[3]s.\x0a\x09\x09\x0aBy using this application" +
	", you agree to the Terms of Service available at %[4]s. This service is " +
	"provided as-is, without any warranty, and is intended for people who wor" +
	"k to make the world a better place.\x0a\x0a\x0a%[1]v version: %[5]s\x02D" +
	"espre\x02Eroare de inițializare\x02Nu am găsit un agent de autentificare" +
	" polkit. Porniți unul și încercați din nou.\x02Lipsește agentul de auten" +
	"tificare\x02Nu se poate conecta la %[1]s: %[2]v\x02Eroare la pornirea VP" +
	"N\x02Verificare stare...\x02Deschidere\x02Închidere\x02Ajutor...\x02Dona" +
	"ție...\x02Despre...\x02Închidere\x02Utilizați gateway-ul %[1]s %[2]v" +
	"\x02Am deschis %[1]s\x02Am închis %[1]s\x02Anulare\x02Conectare la %[1]s" +
	"\x02Oprire %[1]s\x02Reconectare\x02%[1]s blochează accesul la internet" +
	"\x02A apărut o eroare la inițializarea VPN: %[1]v"

var ruIndex = []uint32{ // 27 elements
	0x00000000, 0x00000203, 0x0000022d, 0x000003fc,
	0x00000414, 0x0000043c, 0x000004ec, 0x0000052b,
	0x00000568, 0x00000588, 0x000005ab, 0x000005bc,
	0x000005cf, 0x000005df, 0x0000060c, 0x00000627,
	0x00000632, 0x00000660, 0x0000066e, 0x0000067e,
	0x0000068f, 0x000006af, 0x000006c8, 0x000006e5,
	0x00000713, 0x00000760, 0x00000760,
} // Size: 132 bytes

const ruData string = "" + // Size: 1888 bytes
	"\x02Служба %[1]s платная. В связи с тем, что мы не хотим сохранять персо" +
	"нальную информацию о Вас, здесь нет регистрации или выставления счёта п" +
	"о этой службе. Но, если Вам хочется сохранить работу этой службы, жертв" +
	"уйте по крайней мере 5$ каждый месяц. Вы хотите пожертвовать в данный м" +
	"омент?\x02Сделать пожертвование\x02%[1]s is an easy, fast, and secure V" +
	"PN service from %[2]s. %[1]s does not require a user account, keep logs," +
	" or track you in any way.\x0a\x09    \x0aThis service is paid for entire" +
	"ly by donations from users like you. Please donate at %[3]s.\x0a\x09\x09" +
	"\x0aBy using this application, you agree to the Terms of Service availab" +
	"le at %[4]s. This service is provided as-is, without any warranty, and i" +
	"s intended for people who work to make the world a better place.\x0a\x0a" +
	"\x0a%[1]v version: %[5]s\x02О приложении\x02Ошибка инициализации\x02Не у" +
	"далось найти агент проверки подлинности polkit. Пожалуйста, запустите о" +
	"дин и попробуйте снова.\x02Отсутствует агент аутентификации\x02Не удает" +
	"ся подключиться к %[1]s: %[2]v\x02Ошибка запуска VPN\x02Проверка статус" +
	"а...\x02Включить\x02Выключить\x02Помощь...\x02Сделать пожертвование..." +
	"\x02О приложении...\x02Выход\x02Используется шлюз %[1]s %[2]v\x02%[1]s в" +
	"кл.\x02%[1]s выкл.\x02Отменить\x02Подключение к %[1]s\x02Остановка %[1]" +
	"s\x02Переподключить\x02%[1]s блокировка интернета\x02Произошла ошибка пр" +
	"и инициализации VPN: %[1]v"

var skIndex = []uint32{ // 27 elements
	0x00000000, 0x0000014a, 0x00000154, 0x00000323,
	0x0000032e, 0x00000347, 0x000003a3, 0x000003b9,
	0x000003ef, 0x00000407, 0x00000419, 0x00000422,
	0x0000042b, 0x00000438, 0x00000445, 0x00000453,
	0x0000045d, 0x0000047b, 0x00000498, 0x000004b5,
	0x000004be, 0x000004e0, 0x000004fc, 0x0000050c,
	0x0000052e, 0x00000555, 0x00000555,
} // Size: 132 bytes

const skData string = "" + // Size: 1365 bytes
	"\x02Služby aplikácie %[1]s sú nákladné na správu. Pretože o vás nechceme" +
	" zbierať osobné informácie, v tejto službe neexistujú žiadne účty ani po" +
	"platky. Ale ak chcete aby naša služba mohla fungovať aj v budúcnosti, pr" +
	"osíme vás, aby ste prispievali aspoň sumou 5 $ mesačne.\x0a\x0aChceli by" +
	" ste prispieť hneď teraz?\x02Prispieť\x02%[1]s is an easy, fast, and sec" +
	"ure VPN service from %[2]s. %[1]s does not require a user account, keep " +
	"logs, or track you in any way.\x0a\x09    \x0aThis service is paid for e" +
	"ntirely by donations from users like you. Please donate at %[3]s.\x0a" +
	"\x09\x09\x0aBy using this application, you agree to the Terms of Service" +
	" available at %[4]s. This service is provided as-is, without any warrant" +
	"y, and is intended for people who work to make the world a better place." +
	"\x0a\x0a\x0a%[1]v version: %[5]s\x02O programe\x02Chyba pri inicializáci" +
	"i\x02Nebolo možné nájsť overovacieho agenta polkit. Prosím, spustite ho " +
	"a skúste to znova.\x02Chýba agent overenia\x02Nebolo možné pripojiť sa k" +
	" aplikácii %[1]s: %[2]v\x02Chyba pri spustení VPN\x02Kontrola stavu..." +
	"\x02Zapnúť\x02Vypnúť\x02Pomocník...\x02Prispieť...\x02O programe...\x02U" +
	"končiť\x02Použiť prístup %[1]s %[2]v\x02Aplikácia %[1]s je zapnutá\x02Ap" +
	"likácia %[1]s je vypnutá\x02Zrušiť\x02Pripájanie sa k aplikácii %[1]s" +
	"\x02Zastavujem aplikáciu %[1]s\x02Znova pripojiť\x02Aplikácia %[1]s blok" +
	"uje internet\x02Pri spustení VPN nastala chyba: %[1]v"

var svIndex = []uint32{ // 27 elements
	0x00000000, 0x00000119, 0x00000120, 0x000002ef,
	0x000002f2, 0x00000305, 0x0000035b, 0x00000377,
	0x0000039a, 0x000003af, 0x000003c6, 0x000003cd,
	0x000003d7, 0x000003e1, 0x000003eb, 0x000003f1,
	0x000003f9, 0x00000415, 0x00000423, 0x00000431,
	0x00000438, 0x0000044c, 0x0000045a, 0x00000466,
	0x0000047f, 0x000004ac, 0x000004ac,
} // Size: 132 bytes

const svData string = "" + // Size: 1196 bytes
	"\x02%[1]s-tjänsten är dyr at driva. Då vi inte vill spara någon av din p" +
	"ersonliga information, så finns det inga konton eller fakturatjänster fö" +
	"r den här tjänsten. Men om du vill att tjänsten ska fortsätta fungera så" +
	" donera minst 5 dollar varje månad\x0a\x09\x0aVill du donera nu?\x02Done" +
	"ra\x02%[1]s is an easy, fast, and secure VPN service from %[2]s. %[1]s d" +
	"oes not require a user account, keep logs, or track you in any way.\x0a" +
	"\x09    \x0aThis service is paid for entirely by donations from users li" +
	"ke you. Please donate at %[3]s.\x0a\x09\x09\x0aBy using this application" +
	", you agree to the Terms of Service available at %[4]s. This service is " +
	"provided as-is, without any warranty, and is intended for people who wor" +
	"k to make the world a better place.\x0a\x0a\x0a%[1]v version: %[5]s\x02O" +
	"m\x02Fel vid initiering\x02Kunde inte hitta polkit authentiseringsagent." +
	" Vänligen starta en och försök igen. \x02Saknar authentiseringsagent\x02" +
	"Kan inte ansluta till %[1]s: %[2]v\x02Fel vid start av VPN\x02Kontroller" +
	"ar status...\x02Starta\x02Stäng av\x02Hjälp...\x02Donera...\x02Om...\x02" +
	"Avsluta\x02Använd %[1]s %[2]v gateway\x02%[1]s startad\x02%[1]s stoppad" +
	"\x02Avbryt\x02Ansluter till %[1]s\x02Stoppar %[1]s\x02Återanslut\x02%[1]" +
	"s blockerar internet\x02Ett fel uppstod vid initiering av VPN: %[1]v"

	// Total table size 22064 bytes (21KiB); checksum: ACB97409
