// Code generated by go generate; DO NOT EDIT.
// This file was generated by vendorize.py
// At 2020-08-20 13:39:50

package config

/* All these constants are defined in the vendor.conf file
 */
const (
	Provider        = "vpnlib.bitmask.net"
	ApplicationName = "DemoLib"
	BinaryName      = "demo-lib"
	Auth            = "sip"
	DonateURL       = ""
	AskForDonations = "false"
	HelpURL         = "https://libraryvpn.org/"
	TosURL          = "https://libraryvpn.org/"
	APIURL          = "https://api.vpnlib.bitmask.net:4430/"
	GeolocationAPI  = "https://getmyip.vpnlib.bitmask.net/json"
)

var Version string

/*

CaCert : a string containing a representation of the provider CA, used to
        sign the webapp and openvpn certificates. should be placed in
        config/[provider]-ca.crt

*/
var CaCert = []byte(`-----BEGIN CERTIFICATE-----
MIIBQzCB6aADAgECAgEBMAoGCCqGSM49BAMCMBcxFTATBgNVBAMTDExFQVAgUm9v
dCBDQTAeFw0yMDA4MDYxOTA3NDRaFw0yNTA4MDYxOTEyNDRaMBcxFTATBgNVBAMT
DExFQVAgUm9vdCBDQTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABIG5POr4cAdK
kTavKpSJr8nW1V7HLpr27qKaShpk1TUy5ipaAlusmavGLxKsPE+i3AMlvf/f6ch3
1MjAtIf5rYujJjAkMA4GA1UdDwEB/wQEAwICpDASBgNVHRMBAf8ECDAGAQH/AgEB
MAoGCCqGSM49BAMCA0kAMEYCIQDXj280LNZbSbi0Y2WvtQrJBUw4wdm8qAeOeuH7
6XiLEwIhAPBRsmst/ujcChsG2t6LpG+p8s4rfIfh8YLo/4qrcc5p
-----END CERTIFICATE-----`)
