#!/usr/bin/env python3

import json
import os
import sys

import configparser

from provider import getBrandingProvider
from provider import getProviderData


VERSION = os.environ.get('VERSION', 'unknown')
SCRIPT = 'generate-debian.py'


def writeOutput(data, outfile):

    with open(outfile, 'w') as outf:
        outf.write(json.dumps(data))

if __name__ == "__main__":
    VENDOR_PATH = os.environ.get('VENDOR_PATH')
    configFile = os.path.join(VENDOR_PATH, 'vendor.conf')
    config = configparser.ConfigParser()
    config.read(configFile)
    provider = os.environ.get('PROVIDER') or getBrandingProvider(config)
    data = getProviderData(provider, config)

    providers_env = os.environ.get('PROVIDERS')
    default_provider_env = os.environ.get('DEFAULT_PROVIDER')

    if providers_env:
        data['providerExport'] = ''
        data['providersExport'] = 'export PROVIDERS={}'.format(providers_env)
    else:
        data['providerExport'] = 'export PROVIDER={}'.format(data['provider'])
        data['providersExport'] = ''

    if default_provider_env is not None:
        data['defaultProviderExport'] = 'export DEFAULT_PROVIDER={}'.format(default_provider_env)
    else:
        data['defaultProviderExport'] = ''

    if len(sys.argv) != 2:
        print('Usage: {} <output_file>'.format(SCRIPT))
        sys.exit(1)

    outputf = sys.argv[1]

    data['version'] = VERSION
    writeOutput(data, outputf)
