#!/bin/sh
# Bitmask Post-Instalation script
# (c) LEAP Encryption access Project
# We copy the bitmask-helper plist to the LaunchDaemons folder, and load the bitmask-helper that runs as root.

LOG=/tmp/$applicationName-install.log

chmod +x /Applications/$applicationName.app/Contents/MacOS/bitmask-helper
cp se.leap.bitmask-helper.plist /Library/LaunchDaemons/ \
	&& echo `date` ":: $applicationName post-install: copied bitmask-helper Plist." >> $$LOG
launchctl load /Library/LaunchDaemons/se.leap.bitmask-helper.plist && echo `date` ":: $applicationName post-install: loaded bitmask-helper." >> $$LOG
chown admin:wheel /Applications/$applicationName.app/Contents/helper
echo `date` ":: $applicationName post-install: ok." >> $$LOG
exit 0
