#!/bin/sh
# Bitmask Pre-Instalation script
# (c) LEAP Encryption access Project
# We unload the bitmask-helper if it is running, because we can be installing an upgrade.

LOG=/tmp/$applicationName-install.log

ps aux | grep [b]itmask-helper \
	&& launchctl unload /Library/LaunchDaemons/se.leap.bitmask-helper.plist \
	&& echo `date` ":: $applicationName pre-install: unloaded bitmask-helper." >> $$LOG
echo `date` ":: $applicationName pre-install: ok." >> $$LOG
exit 0
